name: ci

on:
  push:
  pull_request:
    branches:
    - main

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16.x
      - uses: actions/checkout@v2.3.4
      - run: go vet
      - run: go test